name = "App-DataFactory"
badges = ["github-actions/test.yml"]
module_maker = "ModuleBuildTiny"
static_install = "auto"

[prereqs.runtime]
requires = { "Text::CSV_XS" = "0", "YAML::XS" = "0", "JSON::XS" = "0", "DBI" = "0", "DBD::SQLite" = "0", "Try::Tiny" = "0", "XML::LibXML" = "0" }
